// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/auth/internal"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// internalMenuDao is internal type for wrapping internal DAO implements.
type internalMenuDao = *internal.MenuDao

// menuDao is the data access object for table auth_menu.
// You can define custom methods on it to extend its functionality as you wish.
type menuDao struct {
	internalMenuDao
}

var (
	// Menu is globally public accessible object for table auth_menu operations.
	Menu = menuDao{
		internal.NewMenuDao(),
	}
)

// Fill with you ideas below.
func (dao *menuDao) PrimaryKey() (primaryKey string) {
	//primaryKey = reflect.ValueOf(dao.Columns()).Field(0).String()
	primaryKey = dao.Columns().MenuId
	return
}

func (dao *menuDao) Filter(filter g.MapStrAny, joinCode *[]string) func(m *gdb.Model) *gdb.Model {
	return func(m *gdb.Model) *gdb.Model {
		for k, v := range filter {
			/* if (is_numeric($k) && is_array($v)) {
			       if (!$this->whereOfAlone(...$v)) {
			           $this->whereOfCommon(...$v);
			       }
			   } else {
			       if (!$this->whereOfAlone($k, null, $v)) {
			           $this->whereOfCommon($k, null, $v);
			       }
			   } */
			switch k {
			case "id":
				m = m.Where(dao.Table()+"."+dao.PrimaryKey(), v)
			default:
				m = m.Where(k, v)
			}
		}
		return m
	}
}

func (dao *menuDao) filterOfCommon(m *gdb.Model, key string, operator string, value g.Map, boolean string) *gdb.Model {
	switch key {
	case "id":
		m = m.Where(dao.Table()+"."+dao.PrimaryKey(), value)
	default:
		m = m.Where(key, value)
	}
	return m
}
