variables:
  PROJECT_DIR: $CI_PROJECT_DIR  # GitLab自带预定义变量，表示项目根目录
  DOCKER_IMAGE: "admin:0.0.1"
  DOCKER_TAR: "admin.tar"
  REMOTE_SERVER: "192.168.0.222"
  REMOTE_USER: "jb"
  REMOTE_DIR: "/server/app/admin"
  REMOTE_CONTAINER_NAME: "admin"

stages:
  - vue
  - go
  - docker

buildVue:
  stage: vue
  image: node:22.15.1
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REMOTE_SERVER >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # - ssh-keygen -y -f ~/.ssh/id_rsa # 调试：打印当前私钥的公钥指纹
    # - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v $REMOTE_USER@$REMOTE_SERVER 'echo SSH login successful' # 可选：调试 SSH 是否能登录
    # - npm config set registry=https://registry.npm.taobao.org/before_script:
  script:
    - (cd ./view/platform && npm install && npm run build-only)
    - (cd ./view/org && npm install && npm run build-only)
    - scp -r ./public/admin/* $REMOTE_USER@$REMOTE_SERVER:$REMOTE_DIR/public/admin
  only:
    - master

buildGo:
  stage: go
  image: golang:1.23.1
  before_script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go install github.com/gogf/gf/cmd/gf/v2@v2.9.0
  script:
    - (cd ./api && /go/bin/gf build)
  only:
    - master

buildDocker:
  stage: docker
  image: docker:28.1.1
  # services:
  #   - docker:28.1.1-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375
  #   DOCKER_TLS_CERTDIR: ""  # 关闭 TLS 认证（用于简化）
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REMOTE_SERVER >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # - ssh-keygen -y -f ~/.ssh/id_rsa # 调试：打印当前私钥的公钥指纹
    # - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v $REMOTE_USER@$REMOTE_SERVER 'echo SSH login successful' # 可选：调试 SSH 是否能登录
  script:
    # - docker build -t $DOCKER_IMAGE . && docker save -o $DOCKER_TAR $DOCKER_IMAGE
    - docker build -t $DOCKER_IMAGE .
    - docker save -o $DOCKER_TAR $DOCKER_IMAGE
    - scp $DOCKER_TAR $REMOTE_USER@$REMOTE_SERVER:$REMOTE_DIR
    - ssh $REMOTE_USER@$REMOTE_SERVER "docker compose -f $REMOTE_DIR/compose.yaml down $REMOTE_CONTAINER_NAME && docker load -i $REMOTE_DIR/$DOCKER_TAR && docker compose -f $REMOTE_DIR/compose.yaml up -d $REMOTE_CONTAINER_NAME"
  only:
    - master