# # 安装教程：
#     # 上传文件
#         配置文件：api/manifest
#         前端代码：public/admin
#         镜像文件：admin.tar
#         docker部署文件：compose.yaml
#         nginx配置文件：nginx.conf和admin.conf。注意IP，域名和ssl文件名需修改

#     # 服务器执行以下命令
#         docker load -i /server/app/admin/admin.tar
#         mkdir -p /server/app/admin/public/upload
#         chmod -R 755 /server/app/admin/public/upload
#         # #内网IP和外网IP环境变量.env文件
#         echo -e "SERVER_LOCAL_IP=$(hostname -I | awk '{print $1}')\nSERVER_NETWORK_IP=$(curl -s --max-time 3 ifconfig.me || curl -s --max-time 3 https://ipinfo.io/ip || curl -s --max-time 3 https://checkip.amazonaws.com || curl -s --max-time 3 https://icanhazip.com || curl -s --max-time 3 https://api.ipify.org)" > /server/app/admin/.env
#         # nginx需要
#         mkdir -p /server/tool/nginx/1.27.5/config/web
#         mv /server/app/admin/nginx.conf /server/tool/nginx/1.27.5/config/nginx.conf
#         mv /server/app/admin/admin.conf /server/tool/nginx/1.27.5/config/web/admin.conf
#         # 部署
#         docker compose -f /server/app/admin/compose.yaml up -d

#     # 上传新版本后重启服务命令
#         docker compose -f /server/app/admin/compose.yaml down admin && docker rmi admin:0.0.1 && docker load -i /server/app/admin/admin.tar && docker compose -f /server/app/admin/compose.yaml restart admin

services:
  admin:
    image: admin:0.0.1
    container_name: admin
    restart: unless-stopped
    network_mode: host
    env_file: /server/app/admin/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/app/admin/public:/server/app/admin/public
      - /server/app/admin/api/manifest:/server/app/admin/api/manifest
      - /server/app/admin/api/log:/server/app/admin/api/log
    depends_on:
      - redis-alone
      - mysql-alone

  nginx-alone:
    image: nginx:1.27.5
    container_name: nginx-alone
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/nginx/1.27.5/config/nginx.conf:/etc/nginx/nginx.conf
      - /server/tool/nginx/1.27.5/config/web:/etc/nginx/web
      - /server/app:/server/app
    depends_on:
      - admin

  redis-alone:
    image: redis:8.0.1
    container_name: redis-alone
    restart: unless-stopped
    network_mode: host
    command: ["redis-server", "--requirepass", "密码"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/redis/8.0.1/data:/data

  mysql-alone:
    image: mysql:9.3.0
    container_name: mysql-alone
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/mysql/9.3.0/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 密码
      MYSQL_DATABASE: 库名
      MYSQL_USER: 账号
      MYSQL_PASSWORD: 密码