# # 安装教程：
#   # 上传文件
#     docker部署文件：compose.tool.yaml
#     nginx配置文件：nginx.conf和项目名.conf。注意IP，域名和ssl文件名需修改

#   # 服务器执行以下命令
#     # nginx需要
#       mkdir -p /server/tool/nginx/1.27.5/config/web
#       mv /server/app/项目名/deploy/nginx/nginx.conf /server/tool/nginx/1.27.5/config/nginx.conf
#       mv /server/app/项目名/deploy/nginx/项目名.conf /server/tool/nginx/1.27.5/config/web/项目名.conf
#     # mysql需要
#       mkdir -p /server/tool/mysql/9.3.0 && chmod -R 777 /server/tool/mysql/9.3.0
#     # postgresql需要
#       mkdir -p /server/tool/postgresql/17.5.0 && chmod -R 777 /server/tool/postgresql/17.5.0
#     # 部署
#       docker compose -f /server/app/项目名/deploy/docker/compose.tool.yaml up -d

services:
  nginx-alone:
    image: nginx:1.27.5
    container_name: nginx-alone
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/nginx/1.27.5/config/nginx.conf:/etc/nginx/nginx.conf
      - /server/tool/nginx/1.27.5/config/web:/etc/nginx/web
      - /server/app:/server/app

#   mysql-alone:
#     image: mysql:9.3.0
#     container_name: mysql-alone
#     restart: unless-stopped
#     network_mode: host
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /server/tool/mysql/9.3.0/data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: 密码
#       MYSQL_DATABASE: 库名
#       MYSQL_USER: 账号
#       MYSQL_PASSWORD: 密码

  mysql-node:
    image: bitnami/mysql:9.3.0
    container_name: mysql-node
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/mysql/9.3.0:/bitnami/mysql # 宿主机需先创建目录，并赋予写入权限：mkdir -p /server/tool/mysql/9.3.0 && chmod -R 777 /server/tool/mysql/9.3.0
    environment:
      MYSQL_PORT_NUMBER: 3306
      MYSQL_ROOT_USER: 账号
      MYSQL_ROOT_PASSWORD: 密码
      MYSQL_DATABASE: 库名
      MYSQL_USER: 账号
      MYSQL_PASSWORD: 密码
      MYSQL_REPLICATION_MODE: master或slave
      MYSQL_REPLICATION_USER: 复制用户
      MYSQL_REPLICATION_PASSWORD: 复制密码
      MYSQL_MASTER_HOST: 主库IP（从库设置）
      MYSQL_MASTER_PORT_NUMBER: 主库端口（从库设置）
      MYSQL_MASTER_ROOT_USER: 主库账号（从库设置）
      MYSQL_MASTER_ROOT_PASSWORD: 主库密码（从库设置）

#   postgresql-alone:
#     image: postgres:17.4
#     container_name: postgresql-alone
#     restart: unless-stopped
#     network_mode: host
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /server/tool/postgresql/17.4/data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: 账号
#       POSTGRES_PASSWORD: 密码
#       MYSQL_DATABASE: 库名

  postgresql-node:
    image: bitnami/postgresql:17.5.0
    container_name: postgresql-node
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/postgresql/17.5.0:/bitnami/postgresql # 宿主机需先创建目录，并赋予写入权限：mkdir -p /server/tool/postgresql/17.5.0 && chmod -R 777 /server/tool/postgresql/17.5.0
    environment:
      POSTGRESQL_PORT_NUMBER: 5432
      POSTGRESQL_USERNAME: 账号
      POSTGRESQL_PASSWORD: 密码
      POSTGRESQL_DATABASE: 库名
      POSTGRESQL_REPLICATION_MODE: master或slave
      POSTGRESQL_REPLICATION_USER: 复制用户
      POSTGRESQL_REPLICATION_PASSWORD: 复制密码
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 0（同步复制副本数量，需从库确认主库才提交事务）
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: on或remote_write或remote_apply（越后面越安全） 
      POSTGRESQL_MASTER_HOST: 主库IP（从库设置）
      POSTGRESQL_MASTER_PORT: 主库端口（从库设置）

  redis-alone:
    image: redis:8.0.1
    container_name: redis-alone
    restart: unless-stopped
    network_mode: host
    command: ["redis-server", "--requirepass", "密码"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /server/tool/redis/8.0.1/data:/data