// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RoleRelToAction is the golang structure of table auth_role_rel_to_action for DAO operations like Where/Data.
type RoleRelToAction struct {
	g.Meta     `orm:"table:auth_role_rel_to_action, do:true"`
	RoleId     interface{} // 权限角色ID
	ActionId   interface{} // 权限操作ID
	UpdateTime *gtime.Time // 更新时间
	CreateTime *gtime.Time // 创建时间
}
