// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package admin

import (
	"api/internal/cache"
	"api/internal/consts"
	daoIndex "api/internal/dao"
	"api/internal/dao/admin/allow"
	"api/internal/dao/admin/internal"
	daoAuth "api/internal/dao/auth"
	daoOrg "api/internal/dao/org"
	"api/internal/utils"
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"sync"

	"github.com/gogf/gf/v2/container/gvar"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/text/gstr"
	"github.com/gogf/gf/v2/util/gconv"
)

func init() {
	allow.RegisterAdmin(&Admin)
}

// adminDao is the data access object for the table admin.
// You can define custom methods on it to extend its functionality as needed.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is a globally accessible object for table admin operations.
	Admin = adminDao{internal.NewAdminDao()}
)

// 获取daoModel
func (daoThis *adminDao) CtxDaoModel(ctx context.Context, dbOpt ...any) *daoIndex.DaoModel {
	return daoIndex.NewDaoModel(ctx, daoThis, dbOpt...)
}

// 解析分库
func (daoThis *adminDao) ParseDbGroup(ctx context.Context, dbGroupOpt ...any) string {
	group := daoThis.Group()
	// 分库逻辑
	/* if len(dbGroupOpt) > 0 {
	} */
	return group
}

// 解析分表
func (daoThis *adminDao) ParseDbTable(ctx context.Context, dbTableOpt ...any) string {
	table := daoThis.Table()
	// 分表逻辑
	/* if len(dbTableOpt) > 0 {
	} */
	return table
}

// 解析Id（未使用代码自动生成，且id字段不在第1个位置时，需手动修改）
func (daoThis *adminDao) ParseId(daoModel *daoIndex.DaoModel) string {
	return daoModel.DbTable + `.` + daoThis.Columns().AdminId
}

// 解析Label（未使用代码自动生成，且id字段不在第2个位置时，需手动修改）
func (daoThis *adminDao) ParseLabel(daoModel *daoIndex.DaoModel) string {
	return fmt.Sprintf(`COALESCE( NULLIF( %s, '' ), NULLIF( %s, '' ), NULLIF( %s, '' ), NULLIF( %s, '' ) )`, daoModel.DbTable+`.`+daoThis.Columns().Phone, daoModel.DbTable+`.`+daoThis.Columns().Email, daoModel.DbTable+`.`+daoThis.Columns().Account, daoModel.DbTable+`.`+daoThis.Columns().Nickname)
}

// 解析filter
func (daoThis *adminDao) ParseFilter(filter map[string]any, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		for k, v := range filter {
			switch k {
			/* case `xxxx`:
			tableXxxx := Xxxx.ParseDbTable(m.GetCtx())
			m = m.Where(tableXxxx+`.`+k, v)
			m = m.Handler(daoThis.ParseJoin(tableXxxx, daoModel)) */
			case `id`, `id_arr`:
				m = m.Where(daoModel.DbTable+`.`+daoThis.Columns().AdminId, v)
			case `exc_id`, `exc_id_arr`:
				if gvar.New(v).IsSlice() {
					m = m.WhereNotIn(daoModel.DbTable+`.`+daoThis.Columns().AdminId, v)
				} else {
					m = m.WhereNot(daoModel.DbTable+`.`+daoThis.Columns().AdminId, v)
				}
			case `label`:
				m = m.Where(m.Builder().WhereLike(daoModel.DbTable+`.`+daoThis.Columns().Phone, `%`+gconv.String(v)+`%`).WhereOrLike(daoModel.DbTable+`.`+daoThis.Columns().Email, `%`+gconv.String(v)+`%`).WhereOrLike(daoModel.DbTable+`.`+daoThis.Columns().Account, `%`+gconv.String(v)+`%`).WhereOrLike(daoModel.DbTable+`.`+daoThis.Columns().Nickname, `%`+gconv.String(v)+`%`))
			case daoAuth.RoleRelOfAdmin.Columns().RoleId:
				tableAuthRoleRelOfAdmin := daoAuth.RoleRelOfAdmin.ParseDbTable(m.GetCtx())
				m = m.Where(tableAuthRoleRelOfAdmin+`.`+k, v)
				m = m.Handler(daoThis.ParseJoin(tableAuthRoleRelOfAdmin, daoModel))
			case `time_range_start`:
				m = m.WhereGTE(daoModel.DbTable+`.`+daoThis.Columns().CreatedAt, v)
			case `time_range_end`:
				m = m.WhereLTE(daoModel.DbTable+`.`+daoThis.Columns().CreatedAt, v)
			case `platform_update_delete`:
				m = m.Where(m.Builder().Where(m.Builder().Where(daoModel.DbTable+`.`+daoThis.Columns().SceneId, consts.SCENE_ID_PLATFORM).Where(daoModel.DbTable+`.`+daoThis.Columns().IsSuper, 0)).
					WhereOr(m.Builder().Where(daoModel.DbTable+`.`+daoThis.Columns().SceneId, consts.SCENE_ID_ORG).Where(daoModel.DbTable+`.`+daoThis.Columns().IsSuper, 1)))
			default:
				if daoThis.Contains(k) {
					m = m.Where(daoModel.DbTable+`.`+k, v)
				} else {
					m = m.Where(k, v)
				}
			}
		}
		return m
	}
}

// 解析field
func (daoThis *adminDao) ParseField(field []string, fieldWithParam map[string]any, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		for _, v := range field {
			switch v {
			/* case `xxxx`:
			tableXxxx := Xxxx.ParseDbTable(m.GetCtx())
			m = m.Fields(tableXxxx + `.` + v)
			m = m.Handler(daoThis.ParseJoin(tableXxxx, daoModel))
			daoModel.AfterField[v] = struct{}{} */
			case `id`:
				m = m.Fields(daoThis.ParseId(daoModel) + ` AS ` + v)
			case `label`:
				m = m.Fields(daoThis.ParseLabel(daoModel) + ` AS ` + v)
			case daoAuth.Scene.Columns().SceneName:
				tableAuthScene := daoAuth.Scene.ParseDbTable(m.GetCtx())
				m = m.Fields(tableAuthScene + `.` + v)
				m = m.Handler(daoThis.ParseJoin(tableAuthScene, daoModel))
			case Privacy.Columns().Password, Privacy.Columns().Salt:
				tablePrivacy := Privacy.ParseDbTable(m.GetCtx())
				m = m.Fields(tablePrivacy + `.` + v)
				m = m.Handler(daoThis.ParseJoin(tablePrivacy, daoModel))
			case `role_id_arr`:
				m = m.Fields(daoModel.DbTable + `.` + daoThis.Columns().AdminId)
				daoModel.AfterField[v] = struct{}{}
			case `rel_name`:
				m = m.Fields(daoModel.DbTable + `.` + daoThis.Columns().SceneId)
				m = m.Fields(daoModel.DbTable + `.` + daoThis.Columns().RelId)
				daoModel.AfterField[v] = struct{}{}
			default:
				if daoThis.Contains(v) {
					m = m.Fields(daoModel.DbTable + `.` + v)
				} else {
					m = m.Fields(v)
				}
			}
		}
		for k, v := range fieldWithParam {
			switch k {
			default:
				daoModel.AfterField[k] = v
			}
		}
		if len(daoModel.AfterField) > 0 {
			m = m.Hook(daoThis.HookSelect(daoModel))
		}
		return m
	}
}

// 处理afterField
func (daoThis *adminDao) HandleAfterField(ctx context.Context, record gdb.Record, daoModel *daoIndex.DaoModel) {
	for k, v := range daoModel.AfterField {
		switch k {
		case `role_id_arr`:
			roleIdArr, _ := daoAuth.RoleRelOfAdmin.CtxDaoModel(ctx).Filter(daoAuth.RoleRelOfAdmin.Columns().AdminId, record[daoThis.Columns().AdminId]).Array(daoAuth.RoleRelOfAdmin.Columns().RoleId)
			record[k] = gvar.New(roleIdArr.Interfaces())
		case `rel_name`:
			relName := ``
			if record[daoThis.Columns().RelId].Uint() == 0 {
				relName = `平台`
			} else {
				switch record[daoThis.Columns().SceneId].String() {
				// case consts.SCENE_ID_PLATFORM:	// 平台都是0
				case consts.SCENE_ID_ORG:
					// relName, _ = daoOrg.Org.CtxDaoModel(ctx).FilterPri(record[daoThis.Columns().RelId]).ValueStr(daoOrg.Org.Columns().OrgName)
					info, _ := daoOrg.Org.CacheGetInfo(ctx, record[daoThis.Columns().RelId].Uint())
					relName = info[daoOrg.Org.Columns().OrgName].String()
				}
			}
			record[k] = gvar.New(relName)
		default:
			if v == struct{}{} {
				record[k] = gvar.New(nil)
			} else {
				record[k] = gvar.New(v)
			}
		}
	}
}

// hook select
func (daoThis *adminDao) HookSelect(daoModel *daoIndex.DaoModel) gdb.HookHandler {
	return gdb.HookHandler{
		Select: func(ctx context.Context, in *gdb.HookSelectInput) (result gdb.Result, err error) {
			result, err = in.Next(ctx)
			if err != nil || len(result) == 0 {
				return
			}

			var wg sync.WaitGroup
			wg.Add(len(result))
			for _, record := range result {
				go func(record gdb.Record) {
					defer wg.Done()
					daoThis.HandleAfterField(ctx, record, daoModel)
				}(record)
			}
			wg.Wait()
			return
		},
	}
}

// 解析insert
func (daoThis *adminDao) ParseInsert(insert map[string]any, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		for k, v := range insert {
			switch k {
			case daoThis.Columns().Account:
				if gconv.String(v) == `` {
					v = nil
				}
				daoModel.SaveData[k] = v
			case daoThis.Columns().Phone:
				if gconv.String(v) == `` {
					v = nil
				}
				daoModel.SaveData[k] = v
			case daoThis.Columns().Email:
				if gconv.String(v) == `` {
					v = nil
				}
				daoModel.SaveData[k] = v
			case Privacy.Columns().Password, Privacy.Columns().Salt:
				if slices.Contains([]string{``, `0`, `[]`, `{}`}, gconv.String(v)) { //gvar.New(v).IsEmpty()无法验证指针的值是空的数据
					continue
				}
				insertData, ok := daoModel.AfterInsert[`privacy`].(map[string]any)
				if !ok {
					insertData = map[string]any{}
				}
				insertData[k] = v
				daoModel.AfterInsert[`privacy`] = insertData
			case `role_id_arr`:
				daoModel.AfterInsert[k] = v
			default:
				if daoThis.Contains(k) {
					daoModel.SaveData[k] = v
				}
			}
		}
		m = m.Data(daoModel.SaveData)
		if len(daoModel.AfterInsert) > 0 {
			m = m.Hook(daoThis.HookInsert(daoModel))
		}
		return m
	}
}

// hook insert
func (daoThis *adminDao) HookInsert(daoModel *daoIndex.DaoModel) gdb.HookHandler {
	return gdb.HookHandler{
		Insert: func(ctx context.Context, in *gdb.HookInsertInput) (result sql.Result, err error) {
			result, err = in.Next(ctx)
			if err != nil {
				return
			}
			id, _ := result.LastInsertId()

			for k, v := range daoModel.AfterInsert {
				switch k {
				case `privacy`:
					insertData, _ := v.(map[string]any)
					insertData[Privacy.Columns().AdminId] = id
					Privacy.CtxDaoModel(ctx).HookInsert(insertData).Insert()
				case `role_id_arr`:
					vArr := gconv.SliceAny(v)
					insertList := make([]map[string]any, len(vArr))
					for index, item := range vArr {
						insertList[index] = map[string]any{daoAuth.RoleRelOfAdmin.Columns().AdminId: id, daoAuth.RoleRelOfAdmin.Columns().RoleId: item}
					}
					daoAuth.RoleRelOfAdmin.CtxDaoModel(ctx).Data(insertList).Insert()
				}
			}
			return
		},
	}
}

// 解析update
func (daoThis *adminDao) ParseUpdate(update map[string]any, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		for k, v := range update {
			switch k {
			case daoThis.Columns().Account:
				if gconv.String(v) == `` {
					v = nil
				}
				daoModel.SaveData[k] = v
			case daoThis.Columns().Phone:
				if gconv.String(v) == `` {
					v = nil
				}
				daoModel.SaveData[k] = v
			case daoThis.Columns().Email:
				if gconv.String(v) == `` {
					v = nil
				}
				daoModel.SaveData[k] = v
			case Privacy.Columns().Password, Privacy.Columns().Salt:
				updateData, ok := daoModel.AfterUpdate[`privacy`].(map[string]any)
				if !ok {
					updateData = map[string]any{}
				}
				updateData[k] = v
				daoModel.AfterUpdate[`privacy`] = updateData
			case `role_id_arr`:
				daoModel.AfterUpdate[k] = v
			default:
				if daoThis.Contains(k) {
					daoModel.SaveData[k] = v
				}
			}
		}
		m = m.Data(daoModel.SaveData)
		// if len(daoModel.AfterUpdate) > 0 {
		m = m.Hook(daoThis.HookUpdate(daoModel))
		if len(daoModel.SaveData) == 0 { //解决主表无数据更新无法触发扩展表更新的问题
			m = m.Data(reflect.ValueOf(*daoThis.Columns()).Field(0).String(), struct{}{})
		}
		// }
		return m
	}
}

// hook update
func (daoThis *adminDao) HookUpdate(daoModel *daoIndex.DaoModel) gdb.HookHandler {
	return gdb.HookHandler{
		Update: func(ctx context.Context, in *gdb.HookUpdateInput) (result sql.Result, err error) {
			if len(daoModel.SaveData) == 0 {
				result = driver.RowsAffected(0)
			} else {
				result, err = in.Next(ctx)
				if err != nil {
					return
				}
			}

			for k, v := range daoModel.AfterUpdate {
				switch k {
				case `privacy`:
					updateData, _ := v.(map[string]any)
					for _, id := range daoModel.IdArr {
						updateData[Privacy.Columns().AdminId] = id
						Privacy.CtxDaoModel(ctx).HookInsert(updateData).OnConflict(Privacy.Columns().AdminId).Save() // Save()只能触发HookInsert()，但因扩展表（一对一）或中间表（一对一）可能没有自增ID，HookInsert()一般无实际作用！要触发HookUpdate()时使用下方代码，同时注释该行
						// if row, _ := Privacy.CtxDaoModel(ctx).SetIdArr(id).HookUpdate(updateData).UpdateAndGetAffected(); row == 0 { //更新失败，有可能记录不存在，这时做插入操作
						// 	Privacy.CtxDaoModel(ctx).HookInsert(updateData).Insert()
						// }
					}
				case `role_id_arr`:
					// daoIndex.SaveArrRelManyWithSort(ctx, &daoAuth.RoleRelOfAdmin, daoAuth.RoleRelOfAdmin.Columns().AdminId, daoAuth.RoleRelOfAdmin.Columns().RoleId, gconv.SliceAny(daoModel.IdArr), gconv.SliceAny(v)) // 有顺序要求时使用，同时注释下面代码
					valArr := gconv.Strings(v)
					for _, id := range daoModel.IdArr {
						daoIndex.SaveArrRelMany(ctx, &daoAuth.RoleRelOfAdmin, daoAuth.RoleRelOfAdmin.Columns().AdminId, daoAuth.RoleRelOfAdmin.Columns().RoleId, id, valArr)
					}
				}
			}

			row, _ := result.RowsAffected()
			if row == 0 {
				return
			}

			/* for k, v := range daoModel.AfterUpdate {
				switch k {
				case `xxxx`:
					for _, id := range daoModel.IdArr {
						daoModel.CloneNew().SetIdArr(id).HookUpdateOne(k, v).Update()
					}
				}
			} */
			cache.DbData.DelInfoById(ctx, daoModel, gconv.SliceAny(daoModel.IdArr)...)
			return
		},
	}
}

// hook delete
func (daoThis *adminDao) HookDelete(daoModel *daoIndex.DaoModel) gdb.HookHandler {
	return gdb.HookHandler{
		Delete: func(ctx context.Context, in *gdb.HookDeleteInput) (result sql.Result, err error) { //有软删除字段时需改成Update事件
			result, err = in.Next(ctx)
			if err != nil {
				return
			}

			row, _ := result.RowsAffected()
			if row == 0 {
				return
			}

			Privacy.CtxDaoModel(ctx).SetIdArr(daoModel.IdArr).HookDelete().Delete()
			daoAuth.RoleRelOfAdmin.CtxDaoModel(ctx).Filter(daoAuth.RoleRelOfAdmin.Columns().AdminId, daoModel.IdArr). /* SetIdArr(). */ HookDelete().Delete()
			cache.DbData.DelInfoById(ctx, daoModel, gconv.SliceAny(daoModel.IdArr)...)
			return
		},
	}
}

// 解析group
func (daoThis *adminDao) ParseGroup(group []string, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		for _, v := range group {
			switch v {
			case `id`:
				m = m.Group(daoModel.DbTable + `.` + daoThis.Columns().AdminId)
			default:
				if daoThis.Contains(v) {
					m = m.Group(daoModel.DbTable + `.` + v)
				} else {
					m = m.Group(v)
				}
			}
		}
		return m
	}
}

// 解析order
func (daoThis *adminDao) ParseOrder(order []string, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		for _, v := range order {
			v = gstr.Trim(v)
			kArr := gstr.Split(v, `,`)
			k := gstr.Split(kArr[0], ` `)[0]
			switch k {
			case `id`:
				m = m.Order(daoModel.DbTable + `.` + gstr.Replace(v, k, daoThis.Columns().AdminId, 1))
			case daoThis.Columns().UpdatedAt:
				m = m.Order(daoModel.DbTable + `.` + v)
				m = m.OrderDesc(daoModel.DbTable + `.` + daoThis.Columns().AdminId)
			case daoThis.Columns().CreatedAt:
				m = m.Order(daoModel.DbTable + `.` + v)
				m = m.OrderDesc(daoModel.DbTable + `.` + daoThis.Columns().AdminId)
			default:
				if daoThis.Contains(k) {
					m = m.Order(daoModel.DbTable + `.` + v)
				} else {
					m = m.Order(v)
				}
			}
		}
		return m
	}
}

// 解析join
func (daoThis *adminDao) ParseJoin(joinTable string, daoModel *daoIndex.DaoModel) gdb.ModelHandler {
	return func(m *gdb.Model) *gdb.Model {
		if _, ok := daoModel.JoinTableMap[joinTable]; ok {
			return m
		}
		daoModel.JoinTableMap[joinTable] = struct{}{}
		switch joinTable {
		/* case Xxxx.ParseDbTable(m.GetCtx()):
		m = m.LeftJoin(joinTable, joinTable+`.`+Xxxx.Columns().XxxxId+` = `+daoModel.DbTable+`.`+daoThis.Columns().XxxxId)
		// m = m.LeftJoin(Xxxx.ParseDbTable(m.GetCtx())+` AS `+joinTable, joinTable+`.`+Xxxx.Columns().XxxxId+` = `+daoModel.DbTable+`.`+daoThis.Columns().XxxxId) */
		case daoAuth.Scene.ParseDbTable(m.GetCtx()):
			m = m.LeftJoin(joinTable, joinTable+`.`+daoAuth.Scene.Columns().SceneId+` = `+daoModel.DbTable+`.`+daoThis.Columns().SceneId)
		case Privacy.ParseDbTable(m.GetCtx()):
			m = m.LeftJoin(joinTable, joinTable+`.`+Privacy.Columns().AdminId+` = `+daoModel.DbTable+`.`+daoThis.Columns().AdminId)
		case daoAuth.RoleRelOfAdmin.ParseDbTable(m.GetCtx()):
			m = m.LeftJoin(joinTable, joinTable+`.`+daoAuth.RoleRelOfAdmin.Columns().AdminId+` = `+daoModel.DbTable+`.`+daoThis.Columns().AdminId)
		default:
			m = m.LeftJoin(joinTable, joinTable+`.`+daoThis.Columns().AdminId+` = `+daoModel.DbTable+`.`+daoThis.Columns().AdminId)
		}
		return m
	}
}

// Add your custom methods and functionality below.

func (daoThis *adminDao) CacheGetInfo(ctx context.Context, id uint) (info gdb.Record, err error) {
	info, err = cache.DbData.GetOrSetInfoById(ctx, daoThis.CtxDaoModel(ctx), id, 0)
	return
}

func (daoThis *adminDao) JoinLoginName(relId uint, loginName string) string {
	if relId == 0 || loginName == `` {
		return loginName
	}
	return fmt.Sprintf(`%d:%s`, relId, loginName)
}

func (daoThis *adminDao) GetLoginName(loginName string) string {
	_, after, found := strings.Cut(loginName, `:`)
	if !found {
		return after
	}
	return loginName
}

func (daoThis *adminDao) GetAdminType(ctx context.Context, sceneId string, relId uint) (adminType uint8, err error) {
	switch sceneId {
	case consts.SCENE_ID_PLATFORM:
		if relId > 0 {
			err = utils.NewErrorCode(ctx, 89999998, ``)
			return
		}
		adminType = 0
	case consts.SCENE_ID_ORG:
		if relId == 0 {
			err = utils.NewErrorCode(ctx, 89999998, ``)
			return
		}
		orgInfo, _ := daoOrg.Org.CacheGetInfo(ctx, relId)
		if orgInfo.IsEmpty() {
			err = utils.NewErrorCode(ctx, 29999997, ``, g.Map{`i18nValues`: []any{g.I18n().T(ctx, `name.org.org`)}})
			return
		}
		adminType = orgInfo[daoOrg.Org.Columns().OrgType].Uint8()
	default:
		err = utils.NewErrorCode(ctx, 39999998, ``)
		return
	}
	return
}
