// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

type (
	IScene interface {
		Count(ctx context.Context, filter map[string]interface{}) (count int, err error)
		List(ctx context.Context, filter map[string]interface{}, field []string, order [2]string, offset int, limit int) (list gdb.Result, err error)
	}
)

var (
	localScene IScene
)

func Scene() IScene {
	if localScene == nil {
		panic("implement not found for interface IScene, forgot register?")
	}
	return localScene
}

func RegisterScene(i IScene) {
	localScene = i
}
