// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	ILogin interface {
		EncryptStr(ctx context.Context, sceneCode string, account string) (encryptStr string, err error)
		Login(ctx context.Context, sceneCode string, account string, password string) (token string, err error)
	}
	IUpload interface {
		Sign(ctx context.Context, sceneCode string, account string) (encryptStr string, err error)
		Notify(ctx context.Context, sceneCode string, account string, password string) (token string, err error)
	}
)

var (
	localLogin  ILogin
	localUpload IUpload
)

func Login() ILogin {
	if localLogin == nil {
		panic("implement not found for interface ILogin, forgot register?")
	}
	return localLogin
}

func RegisterLogin(i ILogin) {
	localLogin = i
}

func Upload() IUpload {
	if localUpload == nil {
		panic("implement not found for interface IUpload, forgot register?")
	}
	return localUpload
}

func RegisterUpload(i IUpload) {
	localUpload = i
}
