# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    packSrc: "manifest,resource" # 需要打包资源目录
    output: "../public/" #默认文件名main，也可写成../public/xxxx指定文件名
  gen:
    dao:
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        removePrefix: "auth_"
        daoPath: "dao/auth"
        doPath: "model/do/auth"
        entityPath: "model/entity/auth"
        tables: "auth_test"
        tplDaoIndexPath: "resource/gen/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/gen/gen_dao_template_dao_internal.txt"
        overwriteDao: true
    pbentity:
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        tables: "auth_test"
