# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      # - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      #   group: "default"
      #   removePrefix: "auth_"
      #   daoPath: "dao/auth"
      #   doPath: "model/do/auth"
      #   entityPath: "model/entity/auth"
      #   tables: "auth_scene,auth_action,auth_menu,auth_role"
      #   tplDaoIndexPath: "resource/template/gen_dao_template_dao.txt"
      #   tplDaoInternalPath: "resource/template/gen_dao_template_dao_internal.txt"
      #   # # 关联表不建议使用gen_dao_template_dao.txt和gen_dao_template_dao_internal.txt模板，会产生很多无用代码。用以下方式生成dao
      #   # tables: "auth_action_rel_to_scene,auth_role_rel_of_platform_admin,auth_role_rel_to_action,auth_role_rel_to_menu"
      #   # tplDaoIndexPath: "resource/template/gen_dao_template_dao_rel.txt"
      #   # overwriteDao: true
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        removePrefix: "test_"
        daoPath: "dao/test"
        doPath: "model/do/test"
        entityPath: "model/entity/test"
        tables: "test_test"
        tplDaoIndexPath: "resource/template/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/template/gen_dao_template_dao_internal.txt"
        # overwriteDao: true
