# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      # - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      #   group: "default"
      #   removePrefix: "auth_"
      #   path: "internal"
      #   tables: "auth_action,auth_action_rel_to_scene,auth_menu,auth_role,auth_role_rel_of_platform_admin,auth_role_rel_to_action,auth_role_rel_to_menu,auth_scene"
      #   daoPath: "dao/auth"
      #   tplDaoIndexPath: "resource/template/gen_dao_template_dao.txt"
      #   tplDaoInternalPath: "resource/template/gen_dao_template_dao_internal.txt"
      #   doPath: "model/do/auth"
      #   # tplDaoDoPath: "resource/template/gen_dao_template_do.txt"
      #   entityPath: "model/entity/auth"
      #   # tplDaoEntityPath: "resource/template/gen_dao_template_entity.txt"
      #   # overwriteDao: true
      # - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      #   group: "default"
      #   removePrefix: "platform_"
      #   path: "internal"
      #   tables: "platform_admin,platform_config,platform_corn,platform_server"
      #   daoPath: "dao/platform"
      #   tplDaoIndexPath: "resource/template/gen_dao_template_dao.txt"
      #   tplDaoInternalPath: "resource/template/gen_dao_template_dao_internal.txt"
      #   doPath: "model/do/platform"
      #   # tplDaoDoPath: "resource/template/gen_dao_template_do.txt"
      #   entityPath: "model/entity/platform"
      #   # tplDaoEntityPath: "resource/template/gen_dao_template_entity.txt"
      #   # overwriteDao: true
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        removePrefix: "log_"
        path: "internal"
        tables: "log_http"
        daoPath: "dao/log"
        tplDaoIndexPath: "resource/template/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/template/gen_dao_template_dao_internal.txt"
        doPath: "model/do/log"
        # tplDaoDoPath: "resource/template/gen_dao_template_do.txt"
        entityPath: "model/entity/log"
        # tplDaoEntityPath: "resource/template/gen_dao_template_entity.txt"
        overwriteDao: true
      # - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      #   group: "default"
      #   removePrefix: "test_"
      #   path: "internal"
      #   tables: "test_test"
      #   daoPath: "dao/test"
      #   tplDaoIndexPath: "resource/template/gen_dao_template_dao.txt"
      #   tplDaoInternalPath: "resource/template/gen_dao_template_dao_internal.txt"
      #   doPath: "model/do/test"
      #   # tplDaoDoPath: "resource/template/gen_dao_template_do.txt"
      #   entityPath: "model/entity/test"
      #   # tplDaoEntityPath: "resource/template/gen_dao_template_entity.txt"
      #   # overwriteDao: true
