# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        tables: "auth_action,auth_action_rel_to_scene,auth_menu,auth_role,auth_role_rel_of_platform_admin,auth_role_rel_to_action,auth_role_rel_to_menu,auth_scene"
        removePrefix: "auth_"
        daoPath: "dao/auth"
        doPath: "model/do/auth"
        entityPath: "model/entity/auth"
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        tables: "platform_admin,platform_config,platform_server"
        removePrefix: "platform_"
        daoPath: "dao/platform"
        doPath: "model/do/platform"
        entityPath: "model/entity/platform"
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        tables: "log_request"
        removePrefix: "log_"
        daoPath: "dao/log"
        doPath: "model/do/log"
        entityPath: "model/entity/log"
