# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    packSrc: "resource/i18n,manifest" # 需要打包资源目录。打包前manifest目录下的配置文件需改成正式环境
    # output: "../main"
  gen:
    dao:
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        group: "default"
        removePrefix: ""
        daoPath: "dao/user"
        doPath: "model/do/user"
        entityPath: "model/entity/user"
        tables: "user"
        tplDaoIndexPath: "resource/gen/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/gen/gen_dao_template_dao_internal.txt"
        overwriteDao: false
    pbentity:
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        tables: "auth_test"
