dev: true # 是否开发环境

cronServerNetworkIp: "" # 对应的外网IP服务器将开启定时任务（线上必须设置。多服务器时，开启其中一台服务器即可）
timerServerNetworkIp: "" # 对应的外网IP服务器将开启定时器（线上必须设置。多服务器时，开启其中一台服务器即可）

i18n:
  path: "manifest/i18n" # i18n文件的存储目录路径
  language: "zh-cn" # 默认语言。对应path路径内的文件夹名称或文件名称

logger:
  path: "log/" # 日志文件路径。默认为空，表示关闭，仅输出到终端
  # level: "prod" # 日志输出级别。默认all
  # stdout: false # 日志是否同时输出到终端。默认true
  # file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
  http:
    isRecord: true # 是否记录http请求日志
    maxResBufferLength: 99999999 # 允许记录的最大响应数据长度。正式环境建议设置小点，或0不记录，原因：列表等接口调用频繁且响应数据大，如记录到日志中，很容易把服务器硬盘撑满
    path: "log/http/"
    stdout: false # 日志是否同时输出到终端。默认true

server:
  address: ":20080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  # maxHeaderBytes: "10240" # 请求Header大小限制（Byte）。默认为10KB
  # clientMaxBodySize: 104857600 # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB
  # serverRoot: "../public" # 静态文件服务的目录根路径，配置时自动开启。不用nginx代理且需要静态文件服务时使用
  # formParsingMemory: 1048576 # 解析表单时的缓冲区大小(Byte)，一般不需要配置。默认为1024*1024=1MB
  serverAgent: "JB Admin" # 服务端Agent信息。默认为"GoFrame HTTP Server"。建议修改，防止暴露服务器所用技术
  dumpRouterMap: false # 是否在Server启动时打印所有的路由列表。默认为true
  # graceful: true # 是否开启平滑重启特性，开启时将会在本地增加10000的本地TCP端口用于进程间通信。默认false
  # gracefulTimeout: 10 # 父进程在平滑重启后多少秒退出，默认2秒。若请求耗时大于该值，可能会导致请求中断
  logPath: "log/server/" # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  # logStdout: false # 日志是否输出到终端。默认为true

database:
  logger: # 数据库设置debug=true时生效
    path: "log/sql/"
    # stdout: false # 日志是否输出到终端。默认为true
  default:
    - link: "pgsql:postgres:123456@tcp(0.0.0.0:5432)/dev_admin"
      # role: "master" # 主从配置(master/slave)
      # weight: "100" # 负载均衡权重，用于负载均衡控制，不使用应用层的负载均衡机制请置空
      # prefix: ""
      # charset: "utf8"
      # timezone: "Local"
      maxIdle: "50" # 连接池最大闲置的连接数
      maxOpen: "50" # 连接池最大打开的连接数
      maxLifetime: "30s" # 连接对象可重复使用的时间长度
      debug: true # 开启调试模式。默认为false
      # dryRun: false # ORM空跑(只读不写)
      # timeMaintainDisabled: true # 是否完全关闭时间更新特性，true时CreatedAt/UpdatedAt/DeletedAt都将失效

redis:
  default:
    address: "0.0.0.0:6379"
    # db:      0
    # pass:    ""
