server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    # type: "mysql"
    # host: "0.0.0.0"
    # port: "3306"
    # user: "root"
    # pass: "123456"
    # name: "dev_admin"
    - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      role: "master"
    - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      role: "slave"
