dev: false # 是否开发环境

masterServerNetworkIp: "" # 主服务器外网IP（线上必须设置。多服务器时，只开启其中一台服务器执行某些任务）

i18n:
  path: "manifest/i18n" # i18n文件的存储目录路径
  language: "zh-cn" # 默认语言。对应path路径内的文件夹名称或文件名称

logger:
  path: "log/" # 日志文件路径。默认为空，表示关闭，仅输出到终端
  # level: "prod" # 日志输出级别。默认all
  stdout: false # 日志是否同时输出到终端。默认true
  # file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
  http:
    isRecord: true # 是否记录http请求日志
    maxResBufferLength: 10000 # 允许记录的最大响应数据长度。正式环境建议设置小点，或0不记录，原因：列表等接口调用频繁且响应数据大，如记录到日志中，很容易把服务器硬盘撑满
    path: "log/http/"
    stdout: false # 日志是否同时输出到终端。默认true
    file: "http.log" # 日志文件格式。默认为"{Y-m-d}.log"。开启切分特性，必须固定一个文件名，否则日期切换后，无法删除当天之前的日志
    rotateSize: "50M" # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    # rotateExpire: 0 # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit: 100 # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire: "30d" # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    # rotateBackupCompress: 9 # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
    # rotateCheckInterval: "1h" # 定时器的时间检测间隔，一般不需要设置。默认为1小时
  cql:
    path: "log/cql/" # 数据库设置debug=true时生效
    stdout: false # 日志是否同时输出到终端。默认true
    file: "cql.log" # 日志文件格式。默认为"{Y-m-d}.log"。开启切分特性，必须固定一个文件名，否则日期切换后，无法删除当天之前的日志
    rotateSize: "50M" # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit: 100 # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire: "30d" # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  kafka:
    path: "log/kafka/" # 数据库设置debug=true时生效
    stdout: false # 日志是否同时输出到终端。默认true
    file: "kafka.log" # 日志文件格式。默认为"{Y-m-d}.log"。开启切分特性，必须固定一个文件名，否则日期切换后，无法删除当天之前的日志
    rotateSize: "50M" # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性

server:
  address: ":20080"
  # httpsAddr: ":20443" # TLS/HTTPS配置，同时需要配置证书和密钥。默认关闭。配置格式同上。
  # httpsCertPath: "manifest/ssl/ssl.crt" # TLS/HTTPS证书文件本地路径，建议使用绝对路径。默认关闭
  # httpsKeyPath: "manifest/ssl/ssl.key" # TLS/HTTPS密钥文件本地路径，建议使用绝对路径。默认关闭
  # openapiPath: "/api.json"
  # swaggerPath: "/swagger"
  serverAgent: "JB Admin" # 服务端Agent信息。默认为"GoFrame HTTP Server"。建议修改，防止暴露服务器所用技术
  dumpRouterMap: false # 是否在Server启动时打印所有的路由列表。默认为true
  logPath: "log/server/" # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout: false # 日志是否输出到终端。默认为true
  serverRoot: "../public" # 静态文件服务的目录根路径，配置时自动开启。不用nginx代理且需要静态文件服务时使用
  clientMaxBodySize: 104857600 # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB，可设置0不限制
  # maxHeaderBytes: "10240" # 请求Header大小限制（Byte）。默认为10KB
  # formParsingMemory: 1048576 # 解析表单时的缓冲区大小(Byte)，一般不需要配置。默认为1024*1024=1MB
  # graceful: true # 是否开启平滑重启特性，开启时将会在本地增加10000的本地TCP端口用于进程间通信。默认false
  # gracefulTimeout: 10 # 父进程在平滑重启后多少秒退出，默认2秒。若请求耗时大于该值，可能会导致请求中断

database:
  logger: # 数据库设置debug=true时生效
    path: "log/sql/"
    stdout: false # 日志是否输出到终端。默认为true
    file: "sql.log" # 日志文件格式。默认为"{Y-m-d}.log"。开启切分特性，必须固定一个文件名，否则日期切换后，无法删除当天之前的日志
    rotateSize: "50M" # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
    rotateBackupLimit: 100 # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
    rotateBackupExpire: "30d" # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  default:
    - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      # role: "master" # 主从配置(master/slave)
      # weight: "100" # 负载均衡权重，用于负载均衡控制，不使用应用层的负载均衡机制请置空
      # prefix: ""
      charset: "utf8mb4"
      timezone: "Local"
      maxIdle: "10" # 连接池最大闲置的连接数
      maxOpen: "100" # 连接池最大打开的连接数
      maxLifetime: "30s" # 连接对象可重复使用的时间长度
      # debug: true # 开启调试模式。默认为false
      # dryRun: false # ORM空跑(只读不写)
      timeMaintainDisabled: true # 是否完全关闭时间更新特性，true时CreatedAt/UpdatedAt/DeletedAt都将失效

redis:
  default:
    address: "0.0.0.0:6379"
    # pass:    ""
    # db:      0

# cqlDb:
#   default:
#     hosts: # 设置单个节点IP即可连接整个集群。但建议设置多个节点IP以保证连接稳定
#       - "0.0.0.0:9042"
#     userName: ""
#     password: ""
#     keyspace: "" # 键空间
#     dcName: "" # 数据中心名称。指定当前服务器使用的数据中心
#     dcList: # 数据中心配置。键空间不存在时需设置，当len(dcList) == 1 && dcList[0].dcName == ``时，复制策略默认为SimpleStrategy，否则为NetworkTopologyStrategy
#       - dcName: "" # 数据中心名称
#         replNum: 1 # 副本数量
#     # protoVersion: 0 # 协议版本
#     consistency: 1 # 一致性级别
#     # mumConns: 10 # 每个节点的连接数
#     debug: true # 开启调试模式。默认为false

# kafka:
#   default:
#     hosts:
#       - "0.0.0.0:9092"
#     userName: ""
#     password: ""
#     saslType: "" # 认证方式：PLAIN SCRAM-SHA-256 SCRAM-SHA-512。默认为PLAIN
#     topicList:  # 主题列表。没有时会自动创建
#       - name: "" # 主题名称
#         partNum: 4 # 分区数量
#         replNum: 2 # 副本数量
#     # producerType: "sync" # 生产者类型：sync同步 async异步。默认为async
#     consumerList: # 消费者列表。在api/internal/utils/kafka/consumer目录下根据 groupId 或 topicArr[0] 实现处理器，并设置到 handlerMapOfGroupId 或 handlerMapOfGroupId 全局变量中
#       - groupId: "" # 分组ID
#         # autoCommit: false # 自动提交。默认true
#         number: 4 # 启动数量。groupId不为空时生效，需满足：服务器数量 * 该值 < topicArr的合计分区数量，超出时会有分组相当于没用，处于闲置中
#         topicArr: # 主题。groupId空时，只有第一个主题生效
#           - ""