server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      role: "master"
      #weight: "100" #负载均衡权重，用于负载均衡控制，不使用应用层的负载均衡机制请置空
      #prefix: ""
      #charset: "utf8"
      #timezone: "local"
      #maxIdle: "10" #连接池最大闲置的连接数
      #maxOpen: "10" #连接池最大打开的连接数
      #maxLifetime: "30s" #连接对象可重复使用的时间长度
      debug: true #开启调试模式
      dryRun: true #ORM空跑(只读不写)
    - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      role: "slave"
      debug: true
