dev: true # 是否开发环境

superPlatformAdminId: 1 # 指定平台超级管理员ID

upload:
  callbackEnable: false # 上传插件是否回调服务器。建议：线上(true)，本地(false)
  callbackUrl: "http://jslx.fuhua91.com:20080/upload/notify" #开发环境下，且开启回调时用于指定线上地址用于回调

logger:
  path: "log/"
  level: "all"
  stdout: true

i18n:
  path: "resource/i18n"
  language: "zh-cn"

server:
  address: ":20080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  # maxHeaderBytes:      "10240"                      # 请求Header大小限制（Byte）。默认为10KB
  # clientMaxBodySize:   810241024          # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB
  # formParsingMemory:   1048576            # 解析表单时的缓冲区大小(Byte)，一般不需要配置。默认为1024*1024=1MB
  serverAgent: "JB Admin" # 服务端Agent信息。默认为"GoFrame HTTP Server"。建议修改，防止暴露服务器所用技术
  dumpRouterMap: false # 是否在Server启动时打印所有的路由列表。默认为true
  graceful: true # 是否开启平滑重启特性，开启时将会在本地增加10000的本地TCP端口用于进程间通信。默认false
  gracefulTimeout: 10 # 父进程在平滑重启后多少秒退出，默认2秒。若请求耗时大于该值，可能会导致请求中断
  # logPath:             ""                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  # errorLogEnabled:     true               # 是否记录异常日志信息到日志中。默认为true
  # errorLogPattern:     "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  # accessLogEnabled:    false              # 是否记录访问日志。默认为false
  # accessLogPattern:    "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

database:
  default:
    - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
      # role: "master" # 主从配置(master/slave)
      # weight: "100" # 负载均衡权重，用于负载均衡控制，不使用应用层的负载均衡机制请置空
      # prefix: ""
      # charset: "utf8"
      # timezone: "local"
      # maxIdle: "10" # 连接池最大闲置的连接数
      # maxOpen: "10" # 连接池最大打开的连接数
      # maxLifetime: "30s" # 连接对象可重复使用的时间长度
      debug: true # 开启调试模式
      # dryRun: false # ORM空跑(只读不写)
redis:
  default:
    address: "0.0.0.0:6379"
    # db:      0
    # pass:    ""
